#######################################################################################
# "pnpm install" composite action                                                      #
#--------------------------------------------------------------------------------------#
#   - bench: https://gist.github.com/belgattitude/0ecd26155b47e7be1be6163ecfbb0f0b     #
########################################################################################

name: 'Monorepo install (pnpm)'
description: 'Run pnpm install'
inputs:
  skip-prisma-postinstall-generate:
    description: 'Avoid prisma to automatically generate schema on postinstall'
    required: false
    default: 'true'

runs:
  using: 'composite'

  steps:
    - uses: pnpm/action-setup@v2.2.2

    - name: Get pnpm store directory
      shell: bash
      id: pnpm-cache
      run: |
        echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-cache-

    # Prevent store to grow over time (not needed with yarn)
    - name: Prune pnpm store
      shell: bash
      run: pnpm prune store

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --strict-peer-dependencies --prefer-offline
      env:
        # Other environment variables
        HUSKY: '0' # By default do not run HUSKY install
        PRISMA_SKIP_POSTINSTALL_GENERATE: ${{ inputs.skip-prisma-postinstall-generate }}
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: ${{ inputs.playwright-skip-browser-download }}
