compressionLevel: 0

defaultSemverRangePrefix: ''

enableGlobalCache: false

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org/'

supportedArchitectures:
  cpu:
    - current
  libc:
    - current
  os:
    - current
