changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - '**/*.test.{js,ts}'
  - '**/*.spec.{js,ts}'

defaultSemverRangePrefix: ''

enableGlobalCache: false

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org/'

packageExtensions:
  next-secure-headers@*:
    peerDependencies:
      react: ^18.0.0

supportedArchitectures:
  cpu:
    - current
  os:
    - current

yarnPath: .yarn/releases/yarn-4.0.0-rc.5.cjs
