# yarnrc.yml config explained here https://yarnpkg.com/configuration/yarnrc

defaultSemverRangePrefix: ''

# Let the cache lives in the current project directory so that it can be pruned
# when deps are changed (allows smarter caching on CI for example)
enableGlobalCache: false

# Keep the linker to traditional node-modules.
nodeLinker: node-modules

# Reduces storage size of node_modules, hardlinks-global is a good alternative too
# but sometimes fails with docker.
nmMode: hardlinks-local

# Whenever a package has specified incorrectly its dependencies.
# @link https://yarnpkg.com/configuration/yarnrc#packageExtensions
packageExtensions:
  # link https://github.com/jagaapple/next-secure-headers/pull/54
  'next-secure-headers@*':
    peerDependencies:
      react: ^17.0.0
  # link https://github.com/getsentry/sentry-javascript/pull/4634
  '@sentry/nextjs@*':
    peerDependenciesMeta:
      webpack:
        optional: true

# Allows limiting download of native binaries to specified platforms (ie: swc, esbuild...)
# @link https://yarnpkg.com/configuration/yarnrc#supportedArchitectures
supportedArchitectures:
  cpu:
    - current
  os:
    - current

# Override defaults in yarn, used for workspaces foreach --since.
# @link https://yarnpkg.com/cli/workspaces/foreach
# @link https://yarnpkg.com/configuration/yarnrc#changesetBaseRefs

changesetBaseRefs:
  - 'main'
  - 'origin/main'
  - 'upstream/main'

# https://yarnpkg.com/configuration/yarnrc#changesetIgnorePatterns
changesetIgnorePatterns:
  - '**/*.test.{js,ts}'
  - '**/*.spec.{js,ts}'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: '@yarnpkg/plugin-constraints'

yarnPath: .yarn/releases/yarn-3.2.0.cjs
