module.exports = {
  graphqlSchema: require('./graphql-schema'),
  'import-x': require('./import-x'),
  jest: require('./jest'),
  mdx: require('./mdx'),
  perfectionist: require('./perfectionist'),
  'perfectionist-jsx': require('./perfectionist-jsx'),
  playwright: require('./playwright'),
  'prettier-config': require('./prettier-config'),
  'prettier-plugin': require('./prettier-plugin'),
  performance: require('./performance'),
  react: require('./react'),
  reactQuery: require('./react-query'),
  reactTestingLibrary: require('./rtl'),
  regexp: require('./regexp'),
  'simple-import-sort': require('./simple-import-sort'),
  sonar: require('./sonar'),
  storybook: require('./storybook'),
  tailwind: require('./tailwind'),
  typescript: require('./typescript'),
};
