# Will override root .ncurc.yml
# @link https://github.com/raineorshine/npm-check-updates

reject: [
    # prevent upgrade of package dependencies
    '@tsed/exceptions',
    'dequal',
    '@types/react',
    '@types/react-dom',
  ]
