name: 'Yarn benchmark'
description: 'Bench yarn with compression vs without + action/cache'

on:
  push:
    branches:
      - dev
      - main

  pull_request:
    types:
      - opened
      - synchronize
      - reopened

runs:
  steps:
    - name: Restore yarn cache (no-compress)
      uses: actions/cache@v3
      id: yarn-benchmark-cache-no-compress
      with:
        path: ./.yarn/benchmark-cache/no-compress
        key: yarn-benchmark-cache-no-compress-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          yarn-benchmark-cache-no-compress

    - name: Restore yarn cache (mixed-compress)
      uses: actions/cache@v3
      id: yarn-benchmark-cache-mixed-compress
      with:
        path: ./.yarn/benchmark-cache/mixed-compress
        key: yarn-benchmark-cache-mixed-compress-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          yarn-benchmark-cache-mixed-compress

    - name: Install dependencies (mixed-compress)
      run: |
        mv yarn.lock yarn.lock.backup
        yarn install --inline-builds --mode=skip-build
      env:
        YARN_ENABLE_GLOBAL_CACHE: 'false' # Use local cache folder to keep downloaded archives
        YARN_NM_MODE: 'hardlinks-local' # Hardlinks-(local|global) reduces io / node_modules size
        YARN_CACHE_DIR: './.yarn/benchmark-cache/mixed-compress'
        YARN_COMPRESSION_LEVEL: 'mixed'
        YARN_INSTALL_STATE_PATH: .yarn/install-state-mixed-compress.gz

    - name: Install dependencies (no-compress)
      run: |
        mv yarn.lock yarn.lock.backup
        yarn install --inline-builds --mode=skip-build
      env:
        YARN_ENABLE_GLOBAL_CACHE: 'false' # Use local cache folder to keep downloaded archives
        YARN_NM_MODE: 'hardlinks-local' # Hardlinks-(local|global) reduces io / node_modules size
        YARN_CACHE_DIR: './.yarn/benchmark-cache/no-compress'
        YARN_COMPRESSION_LEVEL: '0'
        YARN_INSTALL_STATE_PATH: .yarn/ci-cache/install-state-no-compress.gz
