# Bench yarn with compression vs without + action/cache
name: 'Yarn benchmark'
on: [push, pull_request]
jobs:
  bench:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Restore yarn cache (no-compress)
        uses: actions/cache@v3
        id: yarn-benchmark-cache-no-compress
        with:
          path: ./.yarn/benchmark-cache/no-compress
          key: yarn-benchmark-cache-no-compress-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-benchmark-cache-no-compress
      - name: Restore yarn cache (mixed-compress)
        uses: actions/cache@v3
        id: yarn-benchmark-cache-mixed-compress
        with:
          path: ./.yarn/benchmark-cache/mixed-compress
          key: yarn-benchmark-cache-mixed-compress-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-benchmark-cache-mixed-compress
      - name: Install dependencies (mixed-compress)
        run: yarn install --immutable --inline-builds --mode=skip-build
        env:
          YARN_ENABLE_GLOBAL_CACHE: 'false' # Prune cache (yarn.lock changes)
          YARN_NM_MODE: 'hardlinks-local'
          YARN_GLOBAL_FOLDER: '.yarn/global-mixed-compress/'
          YARN_CACHE_FOLDER: '.yarn/benchmark-cache/mixed-compress'
          YARN_COMPRESSION_LEVEL: 'mixed'
          YARN_LOCKFILE_FILENAME: 'yarn.mixed-compress.lock'
          YARN_INSTALL_STATE_PATH: .yarn/install-state-mixed-compress.gz
      - name: Remove node_modules
        run: npx -y rimraf "**/node_modules"
      - name: Install dependencies (no-compress)
        run: yarn install --immutable --inline-builds --mode=skip-build
        env:
          YARN_ENABLE_GLOBAL_CACHE: 'false' # Prune cache (yarn.lock changes)
          YARN_NM_MODE: 'hardlinks-local'
          YARN_GLOBAL_FOLDER: '.yarn/global-no-compress/'
          YARN_CACHE_FOLDER: '.yarn/benchmark-cache/no-compress'
          YARN_LOCKFILE_FILENAME: 'yarn.no-compress.lock'
          YARN_COMPRESSION_LEVEL: '0'
          YARN_INSTALL_STATE_PATH: .yarn/install-state-no-compress.gz
